export default function getAllProducts() {
  return [
    {
      id: 'Mens-Casual-001',
      slug: 'Mens-Casual',
      name:  "Mens Casual Premium Slim Fit T-Shirts ",
      category: 'Men\'s Shirts',
      price: 300_000,
      stock: 100,
      imageUrl: '/assets/images/kemeja.jpg',
      description: "Slim-fitting style, contrast raglan long sleeve, three-button henley placket, light weight & soft fabric for breathable and comfortable wearing. And Solid stitched shirts with round neck made for durability and a great fit for casual fashion wear and diehard baseball fans. The Henley style round neckline includes a three-button placket.",
    },
    {
      id: 'Mens-Cotton-001',
      slug: 'Mens-Cotton',
      name: "Mens Cotton kaos distro",
      category: 'Men\'s Shirts',
      price: 400_000,
      stock: 100,
      imageUrl: '/assets/images/kaos3.jpg',
      description: 'A men’s t-shirt is a versatile and comfortable clothing item designed to suit various casual and semi-casual occasions. Typically made from high-quality fabrics like cotton, polyester, or blends, these t-shirts offer breathability and durability for everyday wear.great outerwear jackets for Spring/Autumn/Winter, suitable for many occasions, such as working, hiking, camping, mountain/rock climbing, cycling, traveling or other outdoors. Good gift choice for you or your family member. A warm hearted love to Father, husband or son in this thanksgiving or Christmas Day.',
    },
    {
      id: 'Mens-Casual-slim-002',
      slug: 'Mens-Casual-slim',
      name:  "Mens baju distro",
      category: 'Men\'s Shirts',
      price: 350_000,
      stock: 5,
      imageUrl: '/assets/images/kaos4.jpg',
      description: 'A men’s t-shirt is a versatile and comfortable clothing item designed to suit various casual and semi-casual occasions. Typically made from high-quality fabrics like cotton, polyester, or blends, these t-shirts offer breathability and durability for everyday wear. color could be slightly different between on the screen and in practice. / Please note that body builds vary by person, therefore, detailed size information should be reviewed below on the product description.',
    },
    {
      id: 'baju-Casual-001',
      slug: 'baju-Casual',
      name: 'sweter',
      category: 'Men\'s Shirts',
      price: 400_000,
      stock: 0,
      imageUrl: '/assets/images/sweter.jpg',
      description: "Satisfaction Guaranteed. ReA men’s t-shirt is a versatile and comfortable clothing item designed to suit various casual and semi-casual occasions. Typically made from high-quality fabrics like cotton, polyester, or blends, these t-shirts offer breathability and durability for everyday wearturn or exchange any order within 30 days.Designed and sold by Hafeez Center in the United States. Satisfaction Guaranteed. Return or exchange any order within 30 days.",
    },
    {
      id: 'BIYLACLESEN Womens-001',
      slug: 'BIYLACLESEN-Womens',
      name: 'BIYLACLESEN Womens 2-in-1 ',
      category: 'Women\'s Shirt',
      price: 200_000,
      stock: 100,
      imageUrl: '/assets/images/baju 12.jpg',
      description: `Note:The blouse features a stylish button-down front, a flattering V-neckline, and a relaxed fit that makes it comfortable yet elegant. Ideal for both work and casual Jackets is US standard size, Please choose size as your usual wear Material: 100% Polyester; Detachable Liner Fabric: Warm Fleece. Detachable Functional Liner: Skin Friendly, Lightweigt and Warm.Stand Collar Liner jacket, keep you warm in cold weather. Zippered Pockets: 2 Zippered Hand Pockets, 2 Zippered Pockets on Chest (enough to keep cards or keys)and 1 Hidden Pocket Inside.Zippered Hand Pockets and Hidden Pocket keep your things secure. Humanized Design: Adjustable and Detachable Hood and Adjustable cuff to prevent the wind and water,for a comfortable fit. 3 in 1 Detachable Design provide more convenience, you can separate the coat and inner as needed, or wear it together. It is suitable for different season and help you adapt to different climates,`
    },
    {
      id: 'Bridesmaid-Dress-002',
      slug: 'Bridesmaid-Dress-Elegant',
      name: "Bridesmaid Satin Dress",
      category: 'Women\'s Shirt',
      price: 1_549_000,
      stock: 100,
      imageUrl: '/assets/images/baju13.jpg',
      description: "100% POLYURETHANE(shell) 100% POLYESTER(lining) 75% POLYESTER 25% COTTON (SWEATER), Faux leather material for style and comfort / 2 pockets of front, 2-For-One Hooded denim style faux leather jacket, Button detail on waist / Detail stitching at sides, HAND WASH ONLY / DO NOT BLEACH / LINE DRY / DO NOT IRON"
    },
    {
      id: 'Blouse-Women-004',
      slug: 'Blouse-Women-Elegant',
      name: " Women's Chiffon Blouse",
      category: 'Women\'s Shirt',
      price: 500_00,
      stock: 5,
      imageUrl: `/assets/images/baju11.jpg`,
      description: "Lightweight perfet for trip or casual wear---Long sleeve with hooded, adjustable drawstring waist design. Button and zipper front closure raincoat, fully stripes Lined and The Raincoat has 2 side pockets are a good size to hold all kinds of things, it covers the hips, and the hood is generous but doesn't overdo it.Attached Cotton Lined Hood with Adjustable Drawstrings give it a real styled look.",
    },
    {
      id: 'dress-abaya',
      slug: 'dress-Women',
      name: "dress Women's abaya",
      category: 'Women\'s Shirt',
      price: 400_000,
      stock: 0,
      imageUrl: `/assets/images/baju10.jpg`,
      description: `Comfortable, durable and timeless—it's number 1 for a reason. The classic '80s construction pairs a warm suede upper with neutral accents for style that tracks whether you're on court or on the go.`
    },
  ]
}